name: Build

on:
  push:
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        kind: [ 'linux', 'windows', 'macOS' ]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        shell: bash
        run: |
          # Define some variables for things we need
          release_name="GeneaGrab-${{ matrix.target }}"

          # Build everything
          if [ "${{ matrix.target }}" == "osx-x64" ]; then
            dotnet publish -r "${{ matrix.target }}" -c Release --self-contained -p:PublishDir="$release_name" -p:UseAppHost=true
          
            APP_NAME="GeneaGrab/GeneaGrab.app"
            PUBLISH_OUTPUT_DIRECTORY="GeneaGrab/${release_name}/."
            INFO_PLIST="GeneaGrab/Info.plist"
            ICON_FILE="GeneaGrab/Assets/Logo/GeneaGrab.icns"
            
            if [ -d "$APP_NAME" ]; then
              rm -rf "$APP_NAME"
            fi
            
            mkdir "$APP_NAME"
            
            mkdir "$APP_NAME/Contents"
            mkdir "$APP_NAME/Contents/MacOS"
            mkdir "$APP_NAME/Contents/Resources"
            
            cp "$INFO_PLIST" "$APP_NAME/Contents/Info.plist"
            cp "$ICON_FILE" "$APP_NAME/Contents/Resources/$(basename $ICON_FILE)"
            cp -a "$PUBLISH_OUTPUT_DIRECTORY" "$APP_NAME/Contents/MacOS"
          else
            dotnet publish -r "${{ matrix.target }}" -c Release --self-contained -p:PublishDir="$release_name"
          fi

          # Pack files
          cd GeneaGrab/
          mkdir output
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "output/${release_name}.zip" "./${release_name}/*"
          elif [ "${{ matrix.target }}" == "osx-x64" ]; then
            7z a -tzip "output/${release_name}.zip" "./GeneaGrab.app"
          else
            tar czvf "output/${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: GeneaGrab/output/*
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: GeneaGrab/output/*
          draft: true
